version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-student
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - student-net

  app:
    image: youssefddd/student-management:latest
    container_name: student-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - student-net

volumes:
  mysql_data:

networks:
  student-net:
